# Ejercicio de edades e ingresos

In [ ]:
import numpy as np

Matriz 3x3 de edades entre 20 y 50

In [ ]:
edades = np.random.uniform(
    low=20,
    high=50,
    size=(3,3)
)
edades=np.round(edades,decimals = 0)
edades

array([[22., 27., 26.],
       [49., 28., 32.],
       [48., 33., 23.]])

In [ ]:
ingresos = np.random.uniform(
    low=2000,
    high=5000,
    size=(3,3)
)
ingresos = np.round(ingresos,decimals = 0)
ingresos

array([[3152., 4156., 3631.],
       [4991., 2444., 2355.],
       [3176., 4202., 2777.]])

In [ ]:
a=np.array(edades)
a=a.reshape(9,1)



In [ ]:
b=np.array(ingresos)
b=b.reshape(9,1)

In [ ]:
ab = np.column_stack((a,b))
ab

array([[  22., 3152.],
       [  27., 4156.],
       [  26., 3631.],
       [  49., 4991.],
       [  28., 2444.],
       [  32., 2355.],
       [  48., 3176.],
       [  33., 4202.],
       [  23., 2777.]])

In [ ]:
edad = ab <= 30
edad

array([[ True, False],
       [ True, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False]])

In [ ]:
salario1 = ab >= 2000
salario1

array([[False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True]])

In [ ]:
combina = np.logical_or(edad,salario1)
combina

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [ True,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [ True,  True]])

In [ ]:
combina1 = np.logical_and (combina,edad)
combina1

array([[ True, False],
       [ True, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False]])

In [ ]:
ab[combina]

array([  22., 3152.,   27., 4156.,   26., 3631., 4991.,   28., 2444.,
       2355., 3176., 4202.,   23., 2777.])